services:
  app:
    build:
      context: .
    environment:
      GOMODCACHE: /go/src/app/.modcache
      GOCACHE: /go/src/app/.cache
    volumes:
      - "./app:/go/src/app"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - blog-network

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: blogs
    volumes:
      - "./.service-db:/var/lib/mysql"
    ports:
      - "3333:3306"
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge